# ======================================================================================
# Workflow: Fix Failing Checks
# ======================================================================================
# Usage:
#   - Triggers automatically when a specified workflow (e.g., "Continuous Integration") fails.
#   - Analyzes failure logs to determine the cause.
#
# Setup:
#   - Ensure WARP_API_KEY is set in Repository Secrets.
#   - Update the `workflow_run.workflows` list to match your CI workflow names.
#
# Expected Output:
#   - A new Pull Request containing the fix for the build or test failure.
#   - Comments on the original PR (if applicable) with a link to the fix.
#
# When to use:
#   - Use this to reduce downtime caused by broken builds or flaky tests.
# ======================================================================================
name: Fix Failing Checks

on:
  workflow_run:
    workflows: ["Continuous Integration", "test_e2e.yml"]
    types:
      - completed

jobs:
  fix_failure:
    name: Fix Failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      contents: write
      pull-requests: write
      actions: read
      checks: read
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Get Failure Logs
        id: logs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RUN_ID=${{ github.event.workflow_run.id }}
          echo "Fetching logs for run $RUN_ID"
          # Fetch logs for failed steps. 
          # Note: --log-failed returns the log of the failed steps.
          LOGS=$(gh run view $RUN_ID --log-failed)
          
          if [ -z "$LOGS" ]; then
            echo "No logs found or failed to retrieve logs."
            LOGS="No logs available."
          fi
          
          # Write to a file to handle potential special characters and size
          echo "$LOGS" > failure_logs.txt

      - name: Construct Prompt
        id: prompt
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let logs = '';
            try {
              logs = fs.readFileSync('failure_logs.txt', 'utf8');
            } catch (e) {
              logs = 'Could not read log file.';
            }
            
            const workflowName = '${{ github.event.workflow_run.name }}';
            const repoName = context.repo.repo;
            const branchName = '${{ github.event.workflow_run.head_branch }}';
            
            const prompt = `You are an expert software engineer and the Warp Agent.
            You are tasked with fixing a CI failure in the repository '${repoName}' on branch '${branchName}'.
            
            **Context**:
            - **Workflow**: ${workflowName}
            - **Status**: FAILED
            
            **Failure Logs**:
            \`\`\`
            ${logs.slice(0, 15000)}
            \`\`\`
            (Logs truncated to first 15000 characters if longer)
            
            **Instructions**:
            1.  **Analyze**: Read the logs carefully to identify the specific error (e.g., test failure, lint error, build error).
            2.  **Locate**: Find the files and lines of code responsible for the error.
            3.  **Fix**: Modify the code to resolve the issue.
                -   If it's a test failure, fix the code logic or update the test if the test is incorrect.
                -   If it's a lint error, fix the style.
            4.  **Verify**: Ensure your changes are minimal and targeted.
            5.  **Output**: Do not output the diff. Just explain what you fixed in a concise summary.
            
            **Constraints**:
            -   Do NOT modify the workflow files (.github/workflows/) unless the error is specifically about the workflow configuration.
            -   Focus on the source code.
            `;
            
            core.setOutput('prompt', prompt);

      - name: Run Warp Agent
        uses: warpdotdev/warp-agent-action@main
        id: agent
        with:
          prompt: ${{ steps.prompt.outputs.prompt }}
          warp_api_key: ${{ secrets.WARP_API_KEY }}
          profile: ${{ vars.WARP_AGENT_PROFILE || '' }}

      - name: Create Fix PR
        env:
          GH_TOKEN: ${{ github.token }}
          ORIGINAL_BRANCH: ${{ github.event.workflow_run.head_branch }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          AGENT_OUTPUT: ${{ steps.agent.outputs.agent_output }}
        run: |
          # Check for changes
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes made by Warp Agent."
            exit 0
          fi
          
          echo "Changes detected. Preparing PR."

          FIX_BRANCH="fix/run-$RUN_ID"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git checkout -b "$FIX_BRANCH"
          git add .
          git commit -m "Fix failing checks for run $RUN_ID"
          git push origin "$FIX_BRANCH" --force
          
          # Find associated PR
          PR_JSON=$(gh pr list --head "$ORIGINAL_BRANCH" --json number,title,url --limit 1)
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.[0].number')
          
          BODY="This PR attempts to fix the CI failures in run [$RUN_ID](${{ github.event.workflow_run.html_url }}).
          
          **Agent Output:**
          $AGENT_OUTPUT
          "
          
          if [ "$PR_NUMBER" == "null" ] || [ -z "$PR_NUMBER" ]; then
             echo "No associated PR found. Creating PR against main."
             NEW_PR_URL=$(gh pr create --title "Fix CI Failure for run $RUN_ID" --body "$BODY" --base main --head "$FIX_BRANCH")
             echo "Created PR: $NEW_PR_URL"
          else
             echo "Found original PR #$PR_NUMBER. Creating fix PR targeting the original branch."
             
             # Title and Body for the new PR
             TITLE="Fix CI Failure for PR #$PR_NUMBER"
             
             # Create PR targeting the ORIGINAL_BRANCH
             NEW_PR_URL=$(gh pr create --title "$TITLE" --body "$BODY" --base "$ORIGINAL_BRANCH" --head "$FIX_BRANCH")
             echo "Created Fix PR: $NEW_PR_URL"
             
             # Comment on the original PR
             gh pr comment "$PR_NUMBER" --body "I detected a CI failure. I have created a fix PR: $NEW_PR_URL"
          fi
