# ======================================================================================
# Workflow: Respond to Comment
# ======================================================================================
# Usage:
#   - Comment on a PR or Issue with "@warpdotdev" (or your configured trigger phrase).
#   - You can ask questions or request code changes (e.g., "@warpdotdev fix this typo").
#
# Setup:
#   - Ensure WARP_API_KEY is set in Repository Secrets.
#   - (Optional) Set WARP_TRIGGER_PHRASE variable if you want a custom trigger.
#
# Expected Output:
#   - The Agent replies to your comment with an answer or confirmation.
#   - If code changes were requested, the Agent commits them directly to the PR branch.
#
# When to use:
#   - Use this for interactive coding assistance during code review or issue triage.
# ======================================================================================
name: Respond to Comment

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  respond:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, vars.WARP_TRIGGER_PHRASE || '@warpdotdev') &&
      (
        github.event_name == 'pull_request_review_comment' ||
        (github.event_name == 'issue_comment' && github.event.issue.pull_request)
      )
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Acknowledge Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          COMMENT_ID="${{ github.event.comment.id }}"
          REACTION="eyes"
          
          if [ "${{ github.event_name }}" == "pull_request_review_comment" ]; then
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/pulls/comments/$COMMENT_ID/reactions \
              -f content="$REACTION"
          else
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/issues/comments/$COMMENT_ID/reactions \
              -f content="$REACTION"
          fi

      - name: Checkout PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER="${{ github.event.issue.number }}"
          if [ -z "$PR_NUMBER" ]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
          fi
          
          echo "Checking out PR #$PR_NUMBER"
          gh pr checkout "$PR_NUMBER"

      - name: Construct Prompt
        id: prompt
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const { owner, repo } = context.repo;
            let prNumber;
            if (context.eventName === 'issue_comment') {
              prNumber = context.payload.issue.number;
            } else {
              prNumber = context.payload.pull_request.number;
            }

            // Fetch PR details to provide full context
            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });

            // Get the list of files changed in the PR
            const { data: files } = await github.rest.pulls.listFiles({
              owner,
              repo,
              pull_number: prNumber,
            });
            
            const fileList = files.map(f => f.filename).join(', ');

            const commentBody = context.payload.comment.body;
            const author = context.payload.comment.user.login;

            let prompt = `You are an expert software engineer and the Warp Agent.
            You are responding to a specific request on a Pull Request. Your goal is to implement the requested changes directly in the codebase.

            **Context**:
            - **PR Title**: ${pr.title}
            - **PR Description**: ${pr.body || 'No description provided.'}
            - **Changed Files**: ${fileList}
            - **User Request**: "${commentBody}" (from user @${author})
            `;

            if (context.eventName === 'pull_request_review_comment') {
              const path = context.payload.comment.path;
              const line = context.payload.comment.line;
              const diffHunk = context.payload.comment.diff_hunk;
              prompt += `
            - **Location**: File '${path}' at line ${line}.
            - **Diff Context**:
            \`\`\`diff
            ${diffHunk}
            \`\`\`
            `;
              prompt += `
            **Instructions**:
            1. Read the file at '${path}' to understand the full context around the line.
            `;
            } else {
                prompt += `
            **Instructions**:
            1. Focus your analysis on the changed files (${fileList}) unless the request explicitly mentions other files.
            `;
            }

            prompt += `2. If the user is asking for code changes, implement them.
            3. If the user is asking a question, answer it based on your analysis of the code.
            4. Ensure your changes (if any) are correct and follow the existing style.
            5. Do not output the code diff in your final message; only explain what you changed or answer the question.
            6. Format your response in Markdown.
            7. Your output will be posted as a reply to the user.
            `;

            core.setOutput('prompt', prompt);

      - name: Run Warp Agent
        uses: warpdotdev/warp-agent-action@main
        id: agent
        with:
          prompt: ${{ steps.prompt.outputs.prompt }}
          warp_api_key: ${{ secrets.WARP_API_KEY }}
          profile: ${{ vars.WARP_AGENT_PROFILE || '' }}

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Warp Agent: Address comment"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Reply to Comment
        env:
          GH_TOKEN: ${{ github.token }}
          AGENT_OUTPUT: ${{ steps.agent.outputs.agent_output }}
        run: |
          COMMENT_ID="${{ github.event.comment.id }}"
          
          # If we have output, reply with it.
          if [ -n "$AGENT_OUTPUT" ]; then
             BODY="Warp Agent processed your request.\n\nOutput:\n$AGENT_OUTPUT"
             
             if [ "${{ github.event_name }}" == "pull_request_review_comment" ]; then
               gh api \
                 --method POST \
                 -H "Accept: application/vnd.github+json" \
                 -H "X-GitHub-Api-Version: 2022-11-28" \
                 /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments/$COMMENT_ID/replies \
                 -f body="$BODY"
             else
               gh issue comment ${{ github.event.issue.number }} --body "$BODY"
             fi
          fi
