# ======================================================================================
# Workflow: Auto PR Review
# ======================================================================================
# Usage:
#   - Runs automatically when a Pull Request is opened or marked ready for review.
#   - Analyzes the diff of the PR.
#
# Setup:
#   - Ensure WARP_API_KEY is set in Repository Secrets.
#   - The Agent needs read access to contents and write access to pull-requests.
#
# Expected Output:
#   - Inline comments on the PR diff highlighting potential bugs, security issues, or style improvements.
#   - A general summary comment if applicable.
#
# When to use:
#   - Use this to get immediate feedback on code changes before human review.
# ======================================================================================
name: Auto PR Review

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  review_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }} > pr_diff.txt

      - name: Construct Review Prompt
        id: prompt
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            // Fetch PR details
            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });

            // Read the diff
            const diffContent = fs.readFileSync('pr_diff.txt', 'utf8');

            const prompt = `You are an expert software engineer and code reviewer.
            Your task is to provide a comprehensive code review for Pull Request #${prNumber}.

            **System Context**:
            - The current working directory is already checked out to the PR branch.
            - You have access to the full source code in the current directory.

            **PR Context**:
            - **Title**: ${pr.title}
            - **Description**: ${pr.body || 'No description provided.'}

            **Code Changes (Diff)**:
            \`\`\`diff
            ${diffContent}
            \`\`\`

            **Instructions**:
            1.  **Analyze**: Carefully review the code changes above for:
                -   **Bugs**: Logic errors, potential crashes, edge cases.
                -   **Security**: Vulnerabilities, insecure patterns.
                -   **Performance**: Inefficient algorithms, unnecessary resource usage.
                -   **Readability & Style**: Poor naming, lack of comments, overly complex code.
                -   **Best Practices**: Adherence to language and framework idioms.
            2.  **Comment**:
                -   Use the GitHub CLI (\`gh\`) to leave inline comments on specific lines where you find issues.
                -   Command format: \`gh pr comment ${prNumber} --path "path/to/file" --line <line_number> --body "Your comment"\`
                -   **Crucial**: Ensure the line number corresponds to the line in the *new* version of the file (the right side of the diff).
            3.  **Suggest Changes**:
                -   If you can propose a specific code fix, use a suggestion block in your comment body.
                -   Format:
                    \`\`\`suggestion
                    <your proposed code change>
                    \`\`\`
                -   Example body: "You can simplify this logic:\n\`\`\`suggestion\nconst x = y + 1;\n\`\`\`"
            4.  **Summary**:
                -   After placing inline comments, if you have general feedback that doesn't fit a specific line, post a general comment: \`gh pr comment ${prNumber} --body "Your summary"\`.

            **Goal**: Provide actionable, high-quality feedback to help the author improve the code. Be constructive and specific.
            `;

            core.setOutput('prompt', prompt);

      - name: Run Warp Agent Review
        uses: warpdotdev/warp-agent-action@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          prompt: ${{ steps.prompt.outputs.prompt }}
          warp_api_key: ${{ secrets.WARP_API_KEY }}
          profile: ${{ vars.WARP_AGENT_PROFILE || '' }}
