# ======================================================================================
# Workflow: Suggest Review Fixes
# ======================================================================================
# Usage:
#   - Triggers when a Pull Request Review is submitted.
#   - Reads the review comments and uses the Warp Agent to suggest fixes.
#
# Setup:
#   - Ensure WARP_API_KEY is set in Repository Secrets.
#
# Expected Output:
#   - Inline replies to review comments with code suggestions where applicable.
#
# When to use:
#   - Use this to automatically address simple review comments.
# ======================================================================================
name: Suggest Review Fixes
on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  suggest_review_fixes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch review comments
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { owner, repo } = context.repo;
            const reviewId = context.payload.review.id;
            const prNumber = context.payload.pull_request.number;

            core.info(`Fetching comments for review ${reviewId} on PR #${prNumber}`);

            const { data: comments } = await github.rest.pulls.listCommentsForReview({
              owner, repo,
              pull_number: prNumber,
              review_id: reviewId
            });

            core.info(`Found ${comments.length} comments.`);
            fs.writeFileSync( 'review_comments.json', JSON.stringify(comments, ['id', 'path', 'line', 'start_line', 'body', 'diff_hunk'], 2));

      - name: Construct Prompt
        id: prompt
        uses: actions/github-script@v7
        with:
          script: |
            const prompt = `You have a list of review comments in review_comments.json. For each comment:
            1. Determine if it's a small, straightforward fix (typos, naming, simple refactors, style issues).
            2. If yes: propose a code suggestion (DO NOT modify files directly).
            3. If no (too complex, requires design decisions, unclear): skip it.

            Output a file responses.json with this format:
            {
              "<comment_id>": "Your minimal explanation here, followed by a suggestion block"
            }

            The suggestion block must contain **only the changed code**, with no extra, unchanged context lines before or after the change.

            The format of the suggestion block should be as follows:
            \`\`\`suggestion
            <only the code you are proposing as the replacement for the selected lines>
            \`\`\`

            For suggestions where the original code spans multiple lines, you must also include a \`start_line\` field in the JSON comment representing the first line of the range covered by the suggestion; \`line\` should be the last line of the range.
            `;
            core.setOutput('prompt', prompt);

      - name: Run Warp Agent
        uses: warpdotdev/warp-agent-action@v1
        with:
          warp_api_key: ${{ secrets.WARP_API_KEY }}
          profile: ${{ vars.WARP_AGENT_PROFILE }}
          prompt: ${{ steps.prompt.outputs.prompt }}

      - name: Reply to comments
        uses: actions/github-script@v7
        if: always() # Run even if the agent fails, to try and post what was drafted
        with:
          script: |
            const fs = require('fs');
            if (!fs.existsSync('responses.json')) {
              core.info('No responses.json found.');
              return;
            }

            let responses;
            try {
              responses = JSON.parse(fs.readFileSync('responses.json', 'utf8'));
            } catch (e) {
              core.info('Failed to parse responses.json', e);
              return;
            }

            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            for (const [commentId, reply] of Object.entries(responses)) {
              if (!reply || !reply.includes('```suggestion')) continue;
              
              core.info(`Replying to comment ${commentId}`);
              try {
                await github.rest.pulls.createReplyForReviewComment({
                  owner, repo,
                  pull_number: prNumber,
                  comment_id: Number(commentId),
                  body: reply
                });
              } catch (error) {
                core.error(`Failed to reply to comment ${commentId}:`, error);
              }
            }
